name: Build Configs

on:
  push:
    branches:
    - MattCNC2024
    
  workflow_dispatch:

jobs:
  Build-CNC:
    name: Build CNC Files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: [SKR_PRO]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3  
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO V1_CNC
      id: build_configs
      run: |
        BOARDTMP=SKR_PRO
        echo "::set-output name=filename::V1-CNC-${BOARDTMP}-${VERSION}.bin"
        sed -i "s/#define MOTHERBOARD.*/#define MOTHERBOARD BOARD_BTT_SKR_PRO_V1_2/g" Marlin/Configuration.h
        pio run -e BIGTREE_SKR_PRO
        mkdir temp
        mv .pio/build/BIGTREE_SKR_PRO/*.bin temp/build.bin
      env:
        BOARD: ${{ matrix.board }}
    - name: Push
      uses: actions-x/commit@v6
      with:
        email: 38851044+bigtreetech@users.noreply.github.com
        name: bigtreetech
        message: 📦️ Update prebuilt binaries and config
        token: ${{ secrets.MY_SECRET_TOKEN }}
